[pytest]
testpaths = .
markers =
    positive: Позитивные тест-кейсы
    negative: Негативные тест-кейсы
    corner_case: Граничные и нестандартные случаи
    e2e: Сквозные (end-to-end) сценарии
    nonfunctional: Нефункциональные проверки
